spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hhplus
    #    driverClassName: org.h2.Driver
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_schema: concert
        #    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      port: 6379
      host: localhost
      prefix: "redis://"
#logging:
#  level:
#    org.hibernate.orm.jdbc.bind: trace
