spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concert
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100 #최대 pool 크기
      minimum-idle: 10 #최소 pool 크기
      idle-timeout: 600000 #연결위한 최대 유후 시간
      max-lifetime: 1800000 #반납된 커넥션의 최대 수명

  jpa:
    hibernate:
      ddl-auto:

  sql:
    init:
      mode: always # 서버 시작시 항상 classpath의 sql문을 실행하도록 설정
      continue-on-error: true # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
#      data-locations: classpath:sql/dml.sql # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정
      schema-locations: classpath:sql/ddl.sql # 서버 시작시 ddl sql문을 실행할

  data:
    redis:
      port: 6379
      host: localhost
      prefix: "redis://"

  sleuth:
    otel:
      config:
        trace-id-ratio-based: 0.1
      exporter:
        otlp:
          endpoint: http://10.0.0.106:4317

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger:
    endpoint: 10.0.0.106:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ jaeger ]


#   jmx.enabled: true
# server.tomcat.mbeanregistry.enabled: true
